name: FractureScrim
authors: [Barnyard_Owl, LoveRokenbok]
main: main.Main
version: 0.1
description: >
             Plugin created by Barnyard_Owl and LoveRokenbok for Team Fracture for scrimmaging.
commands: